/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IHM;

import controller.VoyageController;
import entity.Voyage;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayman
 */
public class GestionVoyagesIHM extends javax.swing.JFrame {
    // Contrôleur et modèle de tableau
    private VoyageController voyageController = new VoyageController();
    private DefaultTableModel tableModel;

    public GestionVoyagesIHM() {
        initComponents();
        tableModel = (DefaultTableModel) jTableVoyages.getModel();
    }

    // Méthode pour lister les voyages dans le tableau
    public void listerVoyages() {
        List<Voyage> listeVoyages = voyageController.listerTousVoyages();
        tableModel.setRowCount(0); // Vider le tableau
        for (Voyage voyage : listeVoyages) {
            tableModel.addRow(voyage.toArray());
        }
    }
        private void clearFields() {
        txtDestination.setText("");
        txtPrix.setText("");
        txtAeroportDepart.setText("");
        txtAeroportArrivee.setText("");
        txtPlaces.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVoyages = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmdAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtDestination = new javax.swing.JTextField();
        txtPrix = new javax.swing.JTextField();
        txtAeroportDepart = new javax.swing.JTextField();
        txtAeroportArrivee = new javax.swing.JTextField();
        txtSearchDestination = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPlaces = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jButton1.setText("Gestion Voyages");

        jTableVoyages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "destination", "prix", "aeroport_depart", "aeroport_arrivee", "nbr_places"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVoyages);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel1.setText("Destination    :");

        cmdAdd.setText("Ajouter");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtSearchDestination.setText("Veuillez saisir une destination");
        txtSearchDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchDestinationActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setText("Prix    :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setText("Airoport de départ    :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setText("Airoport d'arrivee    :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel5.setText("Nombre des places    :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Formulaire à remplire :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel7.setText("Chercher Voyages       :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDestination, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrix, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAeroportDepart, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAeroportArrivee, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(txtPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmdAdd)
                                .addGap(128, 128, 128)
                                .addComponent(jButton3)
                                .addGap(100, 100, 100)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(28, 28, 28)
                                .addComponent(txtSearchDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(401, 401, 401))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAeroportDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtAeroportArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdAdd)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listerVoyages();
    }//GEN-LAST:event_formWindowOpened

    private void txtSearchDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchDestinationActionPerformed
            String destination = txtSearchDestination.getText();
    List<Voyage> resultats = voyageController.rechercherParDestination(destination);
    tableModel.setRowCount(0);
    for (Voyage v : resultats) {
        tableModel.addRow(v.toArray());
    }
    }//GEN-LAST:event_txtSearchDestinationActionPerformed

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
    // Récupération des valeurs depuis les champs
    String destination = txtDestination.getText().trim();
    String prixStr = txtPrix.getText().trim();
    String aeroportDepart = txtAeroportDepart.getText().trim();
    String aeroportArrivee = txtAeroportArrivee.getText().trim();
    String placesStr = txtPlaces.getText().trim();

    // Vérification des champs obligatoires
    if(destination.isEmpty() || prixStr.isEmpty() || aeroportDepart.isEmpty() ||
       aeroportArrivee.isEmpty() || placesStr.isEmpty()){
        JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs obligatoires.");
        return;
    }

    try {
        // Conversion des données numériques
        double prix = Double.parseDouble(prixStr);
        int nbPlaces = Integer.parseInt(placesStr);

        // Création de l'objet Voyage (selon votre entité, l’id peut être géré automatiquement)
        Voyage voyage = new Voyage(destination, prix, aeroportDepart, aeroportArrivee, nbPlaces);

        // Création du voyage via le contrôleur
        boolean isCreated = voyageController.ajouterVoyage(voyage);

        if(isCreated){
            JOptionPane.showMessageDialog(null, "Voyage ajouté avec succès.");
            clearFields();       // Vider les champs
            listerVoyages();     // Rafraîchir la liste dans le tableau
        } else {
            JOptionPane.showMessageDialog(null, "Erreur lors de l'ajout du voyage.");
        }
    } catch(NumberFormatException ex){
        JOptionPane.showMessageDialog(null, "Les champs Prix et Nombre de places doivent être numériques.");
    }

    }//GEN-LAST:event_cmdAddActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // Récupérer la ligne sélectionnée
    int selectedRow = jTableVoyages.getSelectedRow();
    
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
            "Veuillez sélectionner un voyage à modifier", 
            "Aucune sélection", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Récupérer l'identifiant du voyage (supposé être dans la première colonne)
    int id = (Integer) tableModel.getValueAt(selectedRow, 0);
    
    // Récupérer les nouvelles valeurs
    String destination = txtDestination.getText().trim();
    String prixStr = txtPrix.getText().trim();
    String aeroportDepart = txtAeroportDepart.getText().trim();
    String aeroportArrivee = txtAeroportArrivee.getText().trim();
    String placesStr = txtPlaces.getText().trim();

    // Validation basique
    if(destination.isEmpty() || prixStr.isEmpty() || aeroportDepart.isEmpty() ||
       aeroportArrivee.isEmpty() || placesStr.isEmpty()){
        JOptionPane.showMessageDialog(this, 
            "Tous les champs doivent être remplis", 
            "Champs manquants", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        double prix = Double.parseDouble(prixStr);
        int nbPlaces = Integer.parseInt(placesStr);

        // Création de l'objet Voyage modifié
        // En fonction de votre entité, veillez à ce que le constructeur prenne l'id en compte
        Voyage voyageModifie = new Voyage(id, destination, prix, aeroportDepart, aeroportArrivee, nbPlaces);

        // Appeler le contrôleur pour la modification
        boolean result = voyageController.modifierVoyage(voyageModifie);
        
        if(result){
            JOptionPane.showMessageDialog(this, 
                "Voyage modifié avec succès", 
                "Succès", 
                JOptionPane.INFORMATION_MESSAGE);
            listerVoyages();  // Rafraîchir la liste
            clearFields();    // Vider les champs
        } else {
            JOptionPane.showMessageDialog(this, 
                "Échec de la modification", 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
        }
    } catch(NumberFormatException ex){
        JOptionPane.showMessageDialog(this, "Les champs Prix et Nombre de places doivent être numériques.");
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // Récupérer la ligne sélectionnée
    int selectedRow = jTableVoyages.getSelectedRow();
    
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
            "Veuillez sélectionner un voyage à supprimer", 
            "Aucune sélection", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Confirmation de suppression
    int confirm = JOptionPane.showConfirmDialog(
        this, 
        "Êtes-vous sûr de vouloir supprimer ce voyage ?",
        "Confirmation de suppression",
        JOptionPane.YES_NO_OPTION);
    
    if(confirm != JOptionPane.YES_OPTION) return;
    
    // Récupérer l'id du voyage (situé dans la première colonne du tableau)
    int id = (Integer) tableModel.getValueAt(selectedRow, 0);
    
    // Appeler le contrôleur pour supprimer le voyage
    boolean result = voyageController.supprimerVoyage(id);
    
    if(result) {
        JOptionPane.showMessageDialog(this, 
            "Voyage supprimé avec succès", 
            "Succès", 
            JOptionPane.INFORMATION_MESSAGE);
        listerVoyages();  // Rafraîchir la liste
        clearFields();    // Vider les champs
    } else {
        JOptionPane.showMessageDialog(this, 
            "Échec de la suppression", 
            "Erreur", 
            JOptionPane.ERROR_MESSAGE); 
    }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionVoyagesIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionVoyagesIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionVoyagesIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionVoyagesIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionVoyagesIHM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVoyages;
    private javax.swing.JTextField txtAeroportArrivee;
    private javax.swing.JTextField txtAeroportDepart;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtPlaces;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtSearchDestination;
    // End of variables declaration//GEN-END:variables
}
