/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IHM;

import controller.ClientController;
import entity.Client;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayman
 */
public class GestionClientIHM extends javax.swing.JFrame {
    
    

    private ClientController clientController = new ClientController();
    private DefaultTableModel tableModel;
    /**
     * Creates new form GestionClientIHM
     */
    public GestionClientIHM() {
        initComponents();
        tableModel = (DefaultTableModel) jTable1.getModel();
    }

    public void listerClients() {
        List<Client> listeClients = clientController.listerTousClients();
        tableModel.setRowCount(0);  // On vide le tableau avant de le remplir
        for (Client client : listeClients) {
            tableModel.addRow(client.toArray());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCin = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtPassport = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmdAdd = new javax.swing.JButton();
        cmdUpdate = new javax.swing.JButton();
        cmdDel = new javax.swing.JButton();
        txtSearchClient = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Gestion Clients");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("CIN    :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setText("Nom    :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setText("Prénom    :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel5.setText("id Passport    :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel6.setText("Telephone    :");

        txtCin.setName("txtCin"); // NOI18N
        txtCin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCinActionPerformed(evt);
            }
        });

        txtNom.setName("txtNom"); // NOI18N

        txtPrenom.setName("txtPrenom"); // NOI18N

        txtPassport.setName("txtPassport"); // NOI18N
        txtPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassportActionPerformed(evt);
            }
        });

        txtTel.setName("txtTel"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CIN", "Nom", "Prenom", "Passport", "Téléphone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("ClientTable"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        cmdAdd.setText("Ajouter");
        cmdAdd.setName("cmdAdd"); // NOI18N
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });

        cmdUpdate.setText("Modifier");
        cmdUpdate.setName("cmdUpdate"); // NOI18N
        cmdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateActionPerformed(evt);
            }
        });

        cmdDel.setText("Supprimer");
        cmdDel.setName("cmdDel"); // NOI18N
        cmdDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDelActionPerformed(evt);
            }
        });

        txtSearchClient.setText("Veillez saisir le CIN du client");
        txtSearchClient.setName("txtSearchClient"); // NOI18N
        txtSearchClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchClientActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel7.setText("Chercher par CIN :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Formulaire à remplire :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTel)
                            .addComponent(txtPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCin)
                            .addComponent(txtNom)
                            .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(cmdAdd)
                .addGap(61, 61, 61)
                .addComponent(cmdUpdate)
                .addGap(83, 83, 83)
                .addComponent(cmdDel)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdDel)
                    .addComponent(cmdUpdate)
                    .addComponent(cmdAdd)
                    .addComponent(txtSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtCinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCinActionPerformed

                                          
    }//GEN-LAST:event_txtCinActionPerformed

    private void txtPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassportActionPerformed

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
           // Récupération des valeurs depuis les champs
    String cin = txtCin.getText().trim();
    String nom = txtNom.getText().trim();
    String prenom = txtPrenom.getText().trim();
    String passport = txtPassport.getText().trim();
    String telephone = txtTel.getText().trim();

    // Vérification des champs obligatoires
    if (cin.isEmpty() || nom.isEmpty() || prenom.isEmpty() || passport.isEmpty() || telephone.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs obligatoires.");
        return;
    }

    // Création du client
    Client client = new Client(
        cin,
        nom,
        prenom,
        passport,
        telephone
    );

    // Création du client via le contrôleur
        System.out.println(client);
    boolean isCreated = clientController.ajouterClient(client);

    if (isCreated) {
        JOptionPane.showMessageDialog(null, "Client ajouté avec succès.");
        
        // Vider les champs après création
        txtCin.setText("");
        txtNom.setText("");
        txtPrenom.setText("");
        txtPassport.setText("");
        txtTel.setText("");
        
        // Rafraîchir la liste
        listerClients();
    } else {
        JOptionPane.showMessageDialog(null, "Erreur lors de l'ajout du client.");
    }
    }//GEN-LAST:event_cmdAddActionPerformed

    private void cmdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateActionPerformed
    // Récupérer la ligne sélectionnée
    int selectedRow = jTable1.getSelectedRow();
    
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
            "Veuillez sélectionner un client à modifier", 
            "Aucune sélection", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Récupérer le CIN original (ne peut pas être modifié)
    String originalCin = (String) tableModel.getValueAt(selectedRow, 0);
    
    // Récupérer les nouvelles valeurs
    String nom = txtNom.getText().trim();
    String prenom = txtPrenom.getText().trim();
    String passport = txtPassport.getText().trim();
    String telephone = txtTel.getText().trim();

    // Validation basique
    if(nom.isEmpty() || prenom.isEmpty() || passport.isEmpty() || telephone.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Tous les champs doivent être remplis", 
            "Champs manquants", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Créer l'objet client modifié
    Client clientModifie = new Client(
        originalCin, // CIN reste inchangé
        nom,
        prenom,
        passport,
        telephone
    );

    // Appeler le contrôleur
    boolean result = clientController.modifierClient(clientModifie);
    
    if(result) {
        JOptionPane.showMessageDialog(this, 
            "Client modifié avec succès", 
            "Succès", 
            JOptionPane.INFORMATION_MESSAGE);
        
        // Rafraîchir la liste
        listerClients();
        clearFields();
    } else {
        JOptionPane.showMessageDialog(this, 
            "Échec de la modification", 
            "Erreur", 
            JOptionPane.ERROR_MESSAGE);
    }
                                     
    }//GEN-LAST:event_cmdUpdateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listerClients();
    }//GEN-LAST:event_formWindowOpened
 
    private void cmdDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDelActionPerformed
        // Récupérer la ligne sélectionnée
    int selectedRow = jTable1.getSelectedRow();
    
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
            "Veuillez sélectionner un client à supprimer", 
            "Aucune sélection", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Confirmation de suppression
    int confirm = JOptionPane.showConfirmDialog(
        this, 
        "Êtes-vous sûr de vouloir supprimer ce client ?",
        "Confirmation de suppression",
        JOptionPane.YES_NO_OPTION);
    
    if(confirm != JOptionPane.YES_OPTION) return;
    
    // Récupérer le CIN du client
    String cin = (String) tableModel.getValueAt(selectedRow, 0);
    
    // Appeler le contrôleur
    boolean result = clientController.supprimerClient(cin);
    
    if(result) {
        JOptionPane.showMessageDialog(this, 
            "Client supprimé avec succès", 
            "Succès", 
            JOptionPane.INFORMATION_MESSAGE);
        
        // Rafraîchir la liste
        listerClients();
        clearFields();
    } else {
        JOptionPane.showMessageDialog(this, 
            "Échec de la suppression", 
            "Erreur", 
            JOptionPane.ERROR_MESSAGE); 
    }
    }//GEN-LAST:event_cmdDelActionPerformed

    private void txtSearchClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchClientActionPerformed
            String searchTerm = txtSearchClient.getText().trim();
    List<Client> clients = clientController.rechercherParCIN(searchTerm);
    
    tableModel.setRowCount(0); // Vider la table
    for (Client client : clients) {
        tableModel.addRow(client.toArray());
    }
    }//GEN-LAST:event_txtSearchClientActionPerformed
    
    private void clearFields(){
        txtCin.setText("");
        txtNom.setText("");
        txtPrenom.setText("");
        txtPassport.setText("");
        txtTel.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionClientIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionClientIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionClientIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionClientIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionClientIHM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdDel;
    private javax.swing.JButton cmdUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCin;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPassport;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtSearchClient;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}

